//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.04 at 03:00:45 PM SGT 
//


package ibevac.datatypes;


import javax.vecmath.Point2d;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CArea complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CArea">
 *   &lt;complexContent>
 *     &lt;extension base="{http://datatypes.evac}CObject">
 *       &lt;sequence>
 *         &lt;element name="corner0" type="{http://datatypes.evac}CPoint"/>
 *         &lt;element name="corner1" type="{http://datatypes.evac}CPoint"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CArea", propOrder = {
    "corner0",
    "corner1"
})
@XmlSeeAlso({
    CRoom.class,
    CFire.class,
    CLink.class,
    CCrowd.class
})
public class CArea
    extends CObject
{

    @XmlElement(required = true)
    protected CPoint corner0;
    @XmlElement(required = true)
    protected CPoint corner1;

    /**
     * Gets the value of the corner0 property.
     * 
     * @return
     *     possible object is
     *     {@link CPoint }
     *     
     */
    public CPoint getCorner0() {
        return corner0;
    }

    /**
     * Sets the value of the corner0 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CPoint }
     *     
     */
    public void setCorner0(CPoint value) {
        this.corner0 = value;
    }

    /**
     * Gets the value of the corner1 property.
     * 
     * @return
     *     possible object is
     *     {@link CPoint }
     *     
     */
    public CPoint getCorner1() {
        return corner1;
    }

    /**
     * Sets the value of the corner1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CPoint }
     *     
     */
    public void setCorner1(CPoint value) {
        this.corner1 = value;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final CArea other = (CArea) obj;
        if(!other.corner0.equals(this.corner0)){
            return false;
        }
        if(!other.corner1.equals(this.corner1)){
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 37 * hash + this.corner0.hashCode();
        hash = 37 * hash + this.corner1.hashCode();
        return hash;
    }

    public Point2d getCenter() {
         return new Point2d(
                (this.corner0.x + this.corner1.x) / 2.0, 
                (this.corner0.y + this.corner1.y) / 2.0);
    }

}
