//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.04 at 03:00:45 PM SGT 
//


package ibevac.datatypes;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CFloor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CFloor">
 *   &lt;complexContent>
 *     &lt;extension base="{http://datatypes.evac}CObject">
 *       &lt;sequence>
 *         &lt;element name="image" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rooms" type="{http://datatypes.evac}CRoom" maxOccurs="unbounded"/>
 *         &lt;element name="links" type="{http://datatypes.evac}CLink" maxOccurs="unbounded"/>
 *         &lt;element name="exits" type="{http://datatypes.evac}CExit" maxOccurs="unbounded"/>
 *         &lt;element name="staircases" type="{http://datatypes.evac}CStaircase" maxOccurs="unbounded"/>
 *         &lt;element name="crowds" type="{http://datatypes.evac}CCrowd" maxOccurs="unbounded"/>
 *         &lt;element name="fires" type="{http://datatypes.evac}CFire" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="height" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CFloor", propOrder = {
    "image",
    "rooms",
    "links",
    "exits",
    "staircases",
    "crowds",
    "fires"
})
public class CFloor
    extends CObject
{

    @XmlElement(required = true)
    protected String image;
    @XmlElement(required = true)
    protected List<CRoom> rooms;
    @XmlElement(required = true)
    protected List<CLink> links;
    @XmlElement(required = true)
    protected List<CExit> exits;
    @XmlElement(required = true)
    protected List<CStaircase> staircases;
    @XmlElement(required = true)
    protected List<CCrowd> crowds;
    @XmlElement(required = true)
    protected List<CFire> fires;
    @XmlAttribute
    protected Integer height;
    @XmlAttribute
    protected Integer width;

    /**
     * Gets the value of the image property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImage() {
        return image;
    }

    /**
     * Sets the value of the image property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImage(String value) {
        this.image = value;
    }

    /**
     * Gets the value of the rooms property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rooms property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRooms().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CRoom }
     * 
     * 
     */
    public List<CRoom> getRooms() {
        if (rooms == null) {
            rooms = new ArrayList<CRoom>();
        }
        return this.rooms;
    }

    /**
     * Gets the value of the links property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the links property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLinks().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CLink }
     * 
     * 
     */
    public List<CLink> getLinks() {
        if (links == null) {
            links = new ArrayList<CLink>();
        }
        return this.links;
    }

    /**
     * Gets the value of the exits property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the exits property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExits().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CExit }
     * 
     * 
     */
    public List<CExit> getExits() {
        if (exits == null) {
            exits = new ArrayList<CExit>();
        }
        return this.exits;
    }

    /**
     * Gets the value of the staircases property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the staircases property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStaircases().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CStaircase }
     * 
     * 
     */
    public List<CStaircase> getStaircases() {
        if (staircases == null) {
            staircases = new ArrayList<CStaircase>();
        }
        return this.staircases;
    }

    /**
     * Gets the value of the crowds property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the crowds property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCrowds().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CCrowd }
     * 
     * 
     */
    public List<CCrowd> getCrowds() {
        if (crowds == null) {
            crowds = new ArrayList<CCrowd>();
        }
        return this.crowds;
    }

    /**
     * Gets the value of the fires property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fires property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFires().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CFire }
     * 
     * 
     */
    public List<CFire> getFires() {
        if (fires == null) {
            fires = new ArrayList<CFire>();
        }
        return this.fires;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHeight(Integer value) {
        this.height = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWidth(Integer value) {
        this.width = value;
    }

}
