//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.04 at 03:00:45 PM SGT 
//


package ibevac.datatypes;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the evac.datatypes package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: evac.datatypes
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CFire }
     * 
     */
    public CFire createCFire() {
        return new CFire();
    }

    /**
     * Create an instance of {@link CObject }
     * 
     */
    public CObject createCObject() {
        return new CObject();
    }

    /**
     * Create an instance of {@link CPoint }
     * 
     */
    public CPoint createCPoint() {
        return new CPoint();
    }

    /**
     * Create an instance of {@link CRoom }
     * 
     */
    public CRoom createCRoom() {
        return new CRoom();
    }

    /**
     * Create an instance of {@link CArea }
     * 
     */
    public CArea createCArea() {
        return new CArea();
    }

    /**
     * Create an instance of {@link CFloor }
     * 
     */
    public CFloor createCFloor() {
        return new CFloor();
    }

    /**
     * Create an instance of {@link CExit }
     * 
     */
    public CExit createCExit() {
        return new CExit();
    }

    /**
     * Create an instance of {@link CLink }
     * 
     */
    public CLink createCLink() {
        return new CLink();
    }

    /**
     * Create an instance of {@link CCrowd }
     * 
     */
    public CCrowd createCCrowd() {
        return new CCrowd();
    }

    /**
     * Create an instance of {@link CStaircase }
     * 
     */
    public CStaircase createCStaircase() {
        return new CStaircase();
    }

    /**
     * Create an instance of {@link CStaircaseGroup }
     * 
     */
    public CStaircaseGroup createCStaircaseGroup() {
        return new CStaircaseGroup();
    }

    /**
     * Create an instance of {@link CEvacuationScenario }
     * 
     */
    public CEvacuationScenario createCEvacuationScenario() {
        return new CEvacuationScenario();
    }

}
